services:
  # Web Service
  - type: web
    name: haatkhata
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      # For NeonDB: Set DATABASE_URL manually in Render dashboard
      # The DATABASE_URL will be set in Render Environment Variables tab
      # Format: postgresql://user:password@ep-xxx.us-east-2.aws.neon.tech/dbname?sslmode=require
      - key: DATABASE_URL
        sync: false  # Will be set manually in Render dashboard
      - key: DB_RETRY_SECONDS
        value: 2
      - key: DB_RETRY_MAX
        value: 10
    healthCheckPath: /health
    autoDeploy: true

# Using external NeonDB - no Render database needed
# Set DATABASE_URL manually in Render dashboard:
# 1. Go to your Render service
# 2. Navigate to Environment tab
# 3. Add DATABASE_URL with your NeonDB connection string
# Format: postgresql://user:password@ep-xxx.us-east-2.aws.neon.tech/dbname?sslmode=require
